<?php

return [
    'brand' => 'Madhusudan Timalsina',
    'name' => 'Madhusudan',
    'full_name' => 'Madhusudan Timalsina',
    'title' => 'Backend Developer',
    'location' => 'Nepal',
    'badge' => 'Backend Developer at Smartsarka · BCIS · Apex College',
    'headline' => 'I build the APIs, databases and server logic that power real products.',
    'bio' => 'Backend Developer at Smartsarka Pvt. Ltd., specializing in Laravel, Node.js, Python, REST APIs and database design. I design reliable server-side systems, model clean data structures and deliver maintainable features for production products.',
    'backend_intro' => 'As a Backend Developer I focus on how data moves, how APIs stay consistent and how authentication, business rules and database design support the product — in production work at Smartsarka, freelance engagements and academic builds.',
    'backend_highlights' => [
        [
            'title' => 'API development',
            'desc' => 'Designing and implementing REST endpoints, request validation and clear response contracts for web and mobile clients.',
        ],
        [
            'title' => 'Laravel backend',
            'desc' => 'Routes, controllers, services, authentication flows and modular features for real application use cases.',
        ],
        [
            'title' => 'Database design',
            'desc' => 'Schema planning, relationships, CRUD systems and administration so data stays consistent and queryable.',
        ],
        [
            'title' => 'Node.js & Python',
            'desc' => 'Server-side scripting and backend services alongside Laravel when the project needs flexible tooling.',
        ],
        [
            'title' => 'Auth & business logic',
            'desc' => 'User flows, permissions-minded structure and server rules that protect data and keep apps predictable.',
        ],
        [
            'title' => 'Freelance backend support',
            'desc' => 'Feature work, bug fixes and database setup for clients who need solid server-side delivery.',
        ],
    ],
    'backend_stack' => ['Laravel', 'Node.js', 'Python', 'REST APIs', 'Database Design', 'SQLite', 'Auth flows', 'CRUD systems'],
    'about_title' => 'Backend Developer',
    'about_intro' => 'I work as a Backend Developer at Smartsarka Pvt. Ltd., building APIs, database systems and server-side features for production applications — while completing my BCIS at Apex College.',
    'about_story' => [
        'I am a Backend Developer at Smartsarka Pvt. Ltd., where I contribute to production server-side systems — APIs, data models, authentication flows and feature delivery that keep products reliable as they grow.',
        'My foundation comes from BCIS studies at Apex College and hands-on builds across book trading, fashion e-commerce, food discovery and fitness tracking. Those projects sharpened how I approach data modeling, API design and shipping under real deadlines.',
        'Alongside my role, I take selective freelance backend work for clients who need Laravel features, database structure or API support. I also mentor peers through the SMART Program and stay active in campus tech leadership.',
    ],
    'about_focus' => [
        'Building and maintaining production APIs and backend services',
        'Designing Laravel applications with clean, modular architecture',
        'Modeling databases for consistency, performance and growth',
        'Implementing authentication, validation and business logic',
        'Supporting clients with focused freelance backend delivery',
        'Collaborating clearly with teams, mentors and stakeholders',
    ],
    'values' => [
        [
            'title' => 'Reliable systems',
            'desc' => 'I prioritize stable APIs, predictable data flows and code that other developers can extend without friction.',
        ],
        [
            'title' => 'Clear contracts',
            'desc' => 'Well-defined endpoints, validation and response shapes make integrations faster for frontend and mobile clients.',
        ],
        [
            'title' => 'Production mindset',
            'desc' => 'From Smartsarka work to freelance projects, I focus on features that are usable, maintainable and ready for real users.',
        ],
        [
            'title' => 'Continuous growth',
            'desc' => 'Mentoring, campus leadership and new tooling keep my backend skills sharp and my collaboration strong.',
        ],
    ],
    'services' => [
        [
            'title' => 'Website development',
            'desc' => 'Business sites, landing pages and content-driven websites with clean layouts and responsive design.',
        ],
        [
            'title' => 'Laravel applications',
            'desc' => 'Custom web apps with authentication, CRUD modules, dashboards and structured database work.',
        ],
        [
            'title' => 'Mobile app UI & Flutter',
            'desc' => 'Cross-platform app screens and flows in Flutter, including local storage with SQLite where needed.',
        ],
        [
            'title' => 'Database design',
            'desc' => 'Schema planning, relationships and administration so your app data stays consistent and queryable.',
        ],
        [
            'title' => 'Frontend implementation',
            'desc' => 'React and modern UI builds that match a design system and feel polished on desktop and mobile.',
        ],
        [
            'title' => 'Freelance support',
            'desc' => 'Short-term feature work, fixes and product improvements for startups, students and small businesses.',
        ],
    ],
    'email' => 'timmadh@gmail.com',
    'email_href' => 'https://mail.google.com/mail/?view=cm&fs=1&to=timmadh@gmail.com',
    'phone' => '+977 9861333037',
    'phone_href' => 'https://wa.me/9779861333037',
    'social' => [
        'linkedin' => 'https://www.linkedin.com/in/madhusudan-timalsina-75a910183/',
    ],
    'palette' => [
        'bg' => '#F3EBD9',
        'ink' => '#2A241C',
        'coral' => '#C4784A',
        'yellow' => '#C4A35A',
        'mint' => '#6B8F71',
        'blue' => '#5B7C8A',
        'card' => '#FFF9F0',
        'soft' => 'rgba(139, 90, 43, 0.12)',
        'surface_1' => '#FFF9F0',
        'surface_2' => '#F3EBD9',
    ],
    'requests' => [
        ['method' => 'GET', 'path' => '/api/profile', 'status' => 200, 'color' => 'mint'],
        ['method' => 'POST', 'path' => '/api/auth/login', 'status' => 201, 'color' => 'yellow'],
        ['method' => 'GET', 'path' => '/api/projects', 'status' => 200, 'color' => 'blue'],
        ['method' => 'PUT', 'path' => '/api/skills', 'status' => 200, 'color' => 'coral'],
    ],
    'stack' => [
        [
            'label' => 'Frontend',
            'icon' => 'layout',
            'color' => 'blue',
            'tools' => ['React', 'Flutter', 'Web Design', 'UI Development', 'Responsive Layout'],
            'blurb' => 'Responsive interfaces for web and mobile, built with clarity and usability in mind.',
            'details' => 'I design and implement user-facing screens for websites and apps — focusing on hierarchy, accessibility of basic interactions and smooth experiences across phone and desktop.',
        ],
        [
            'label' => 'Backend',
            'icon' => 'server',
            'color' => 'coral',
            'tools' => ['Laravel', 'Node.js', 'Python', 'REST APIs', 'Auth flows'],
            'blurb' => 'Application logic, APIs and server-side architecture that keep products stable and scalable.',
            'details' => 'Comfortable building server-side features in Laravel and Node.js, wiring routes, services and form/API handling so the frontend has a solid foundation.',
        ],
        [
            'label' => 'Database',
            'icon' => 'database',
            'color' => 'mint',
            'tools' => ['Database Design', 'SQLite', 'Data Modeling', 'Administration', 'CRUD systems'],
            'blurb' => 'Structured data models and administration so applications stay fast and consistent.',
            'details' => 'From college platforms to personal apps, I plan tables/relationships, manage data integrity and keep admin-facing workflows practical.',
        ],
        [
            'label' => 'Practices',
            'icon' => 'wrench',
            'color' => 'yellow',
            'tools' => ['Design Thinking', 'Problem-Solving', 'Project Management', 'Communication', 'Mentoring'],
            'blurb' => 'Collaborative delivery, clear communication and practical problem-solving across teams.',
            'details' => 'As a class representative and SMART mentor, I practice coordination, feedback and breaking work into shippable pieces — skills I also use with freelance clients.',
        ],
    ],
    'languages' => [
        ['name' => 'Laravel', 'level' => 'Strong project experience', 'note' => 'Used on Yfasma and related web builds'],
        ['name' => 'Flutter', 'level' => 'Strong project experience', 'note' => 'Swaad Sathi and Gym App'],
        ['name' => 'React', 'level' => 'Applied on projects', 'note' => 'Frontend interfaces and component UI'],
        ['name' => 'Node.js', 'level' => 'Applied on projects', 'note' => 'Backend services and API work'],
        ['name' => 'Python', 'level' => 'Working knowledge', 'note' => 'Scripting and backend learning'],
        ['name' => 'React Native', 'level' => 'Project exposure', 'note' => 'Mobile flows on Swaad Sathi'],
    ],
    'soft_skills' => [
        'Strong communication with teammates and stakeholders',
        'Project coordination and deadline awareness',
        'Design thinking and user-focused problem solving',
        'Computer literacy across common development tooling',
        'Leadership as class representative for 42 students',
        'Mentoring and peer support through SMART Program',
    ],
    'projects' => [
        [
            'name' => 'Thrift Books',
            'tag' => 'FULL-STACK',
            'period' => 'Jul–Sep 2023',
            'type' => 'College project',
            'desc' => 'A platform for buying and selling second-hand books with dynamic frontend and backend flows, plus database administration for listings and transactions.',
            'long_desc' => 'Thrift Books was built to make second-hand book trading simpler for students. I worked across website design and database administration so users could browse listings, manage posts and complete buy/sell flows through a dynamic full-stack experience.',
            'highlights' => [
                'End-to-end website design for buying and selling used books',
                'Database administration for listings, users and transactions',
                'Dynamic frontend and backend integration',
                'Focused on a practical campus marketplace use case',
            ],
            'stack' => ['Web Design', 'Database', 'Full-Stack'],
            'color' => 'coral',
            'url' => '#',
        ],
        [
            'name' => 'Yfasma',
            'tag' => 'LARAVEL',
            'period' => 'May–Jul',
            'type' => 'College project',
            'desc' => 'An e-commerce website for affordable designer clothing. Built with Laravel, covering database administration, site structure and end-to-end web delivery.',
            'long_desc' => 'Yfasma is a clothing e-commerce concept that helps users buy designed apparel at affordable prices. I used Laravel to structure the website and database, deepening my understanding of how real Laravel apps are organized from routes to views.',
            'highlights' => [
                'Laravel-based website architecture',
                'Database design and administration for catalog/content',
                'Product-oriented UI for browsing designer clothing',
                'Hands-on practice with Laravel web development patterns',
            ],
            'stack' => ['Laravel', 'Database', 'Web Design'],
            'color' => 'blue',
            'url' => '#',
        ],
        [
            'name' => 'Swaad Sathi',
            'tag' => 'MOBILE',
            'period' => 'May–Jul',
            'type' => 'College project',
            'desc' => 'A mobile app connecting renters with nearby home kitchens. Frontend built with Flutter and React Native, including AI chatbot integration for guided assistance.',
            'long_desc' => 'Swaad Sathi connects people living in rental housing — who often lack time to cook — with home kitchens and cloud-kitchen style providers. I worked on frontend design and development in Flutter and React Native and explored AI chatbot integration with manual training for guided assistance.',
            'highlights' => [
                'Mobile-first experience for renters and home kitchens',
                'Frontend development with Flutter and React Native',
                'AI chatbot integration for guided user help',
                'Solves a real lifestyle problem around daily meals',
            ],
            'stack' => ['Flutter', 'React Native', 'AI Chatbot'],
            'color' => 'mint',
            'url' => '#',
        ],
        [
            'name' => 'Gym App',
            'tag' => 'FLUTTER',
            'period' => 'Sep–Oct',
            'type' => 'Personal project',
            'desc' => 'A personal fitness tracker built with Flutter and SQLite for local activity logging and progress tracking.',
            'long_desc' => 'A personal-use fitness app built to track my own workouts and activity. I implemented the frontend in Flutter and used SQLite for local data storage so progress could be saved offline without a heavy backend.',
            'highlights' => [
                'Flutter frontend for activity tracking',
                'SQLite local database for saving progress',
                'Built for personal daily use and iteration',
                'Practical experience with offline-first mobile data',
            ],
            'stack' => ['Flutter', 'SQLite'],
            'color' => 'yellow',
            'url' => '#',
        ],
    ],
    'freelance' => [
        'intro' => 'Alongside my role at Smartsarka, I take selective freelance backend and product work — helping individuals and small teams ship Laravel features, APIs, database structure and focused UI when needed.',
        'offers' => [
            'Laravel API and feature development',
            'Database schema planning and administration',
            'Authentication and CRUD module setup',
            'Backend bug fixes and performance improvements',
            'Website and admin panel builds',
            'Short technical scoping calls',
        ],
    ],
    'education' => [
        [
            'degree' => 'Bachelor in Computer Information System',
            'school' => 'Apex College',
            'period' => '2020 – Present',
            'details' => 'Studying computer information systems with a focus on software development, databases and practical project work. Coursework and campus projects cover web development, application design and collaborative delivery.',
            'points' => [
                'Active in campus tech events and workshops',
                'Class representative for a cohort of 42 students',
                'Applied classroom concepts through multiple shipped college projects',
            ],
        ],
        [
            'degree' => 'Secondary Level',
            'school' => 'Advance Academy',
            'period' => '2015 – 2017',
            'details' => 'Completed secondary education at Advance Academy, building the academic foundation that led into BCIS and hands-on technology study.',
            'points' => [
                'Strong base for further IT and business-systems study',
                'Continued interest in technology and problem-solving',
            ],
        ],
    ],
    'achievements' => [
        [
            'title' => 'Class representative',
            'desc' => 'Represented a cohort of 42 students — coordinating communication, supporting peers and helping connect classmates with faculty.',
        ],
        [
            'title' => 'SMART Program mentor',
            'desc' => 'Mentored a full section in the SMART Program. The team earned Best Team recognition twice, strengthening my leadership and coaching skills.',
        ],
        [
            'title' => 'SMART Program judge',
            'desc' => 'Participated as a judge in the SMART Program, reviewing work and providing constructive feedback to participating teams.',
        ],
        [
            'title' => 'Campus tech organizer',
            'desc' => 'Helped organize technology events and workshops at college, supporting learning beyond the classroom.',
        ],
        [
            'title' => 'Self-driven learning',
            'desc' => 'Built web development and database skills through self-study alongside formal coursework, then applied them in real projects.',
        ],
        [
            'title' => 'Academic consistency',
            'desc' => 'Maintained strong performance in key IT courses throughout college while balancing projects and leadership roles.',
        ],
    ],
    'process' => [
        [
            'step' => '01',
            'title' => 'Understand the goal',
            'desc' => 'Clarify who the product is for, what problem it solves and what “done” looks like.',
        ],
        [
            'step' => '02',
            'title' => 'Structure the system',
            'desc' => 'Sketch screens, data models and key flows before heavy coding begins.',
        ],
        [
            'step' => '03',
            'title' => 'Build in iterations',
            'desc' => 'Ship usable pieces early — UI, backend and database — then refine with feedback.',
        ],
        [
            'step' => '04',
            'title' => 'Polish and hand off',
            'desc' => 'Clean up edge cases, document basics and make sure the product is ready for real use.',
        ],
    ],
    'nav' => [
        ['label' => 'Home', 'route' => 'home'],
        ['label' => 'About', 'route' => 'about'],
        ['label' => 'Skills', 'route' => 'skills'],
        ['label' => 'Projects', 'route' => 'projects'],
        ['label' => 'Education', 'route' => 'education'],
        ['label' => 'Contact', 'route' => 'contact'],
    ],
    'contact' => [
        'title' => 'Let’s build the backend.',
        'blurb' => 'Currently working as a Backend Developer at Smartsarka Pvt. Ltd. Open to freelance API/database work and collaborative builds in Laravel, Node.js and Python.',
        'availability' => 'Working as a Backend Developer at Smartsarka Pvt. Ltd. since last year. Still available for freelance backend conversations — usually respond within 24–48 hours.',
        'current_role' => [
            'title' => 'Currently working',
            'company' => 'Smartsarka Pvt. Ltd.',
            'role' => 'Backend Developer',
            'duration' => 'Since last year',
            'summary' => 'Building and maintaining server-side systems, APIs and database work in a production environment at Smartsarka Pvt. Ltd.',
            'highlights' => [
                'Backend Developer at Smartsarka Pvt. Ltd.',
                'In this role since last year',
                'Hands-on with APIs, Laravel and production delivery',
                'Open to selective freelance Laravel and API work',
                'Available to discuss backend architecture and collaboration',
            ],
        ],
        'topics' => [
            'REST API design and Laravel backends',
            'Database schema for a new product',
            'Auth, CRUD modules and admin APIs',
            'Node.js / Python backend support',
            'Freelance collaboration alongside current work',
        ],
    ],
    'seo' => [
        'site_url' => 'https://madhusudantimalsina.com.np',
        'site_name' => 'Madhusudan Timalsina',
        'default_title' => 'Madhusudan Timalsina | Backend Developer',
        'default_description' => 'Backend Developer at Smartsarka Pvt. Ltd. specializing in Laravel, Node.js, Python, REST APIs and database design. Hire Madhusudan Timalsina for production backend and freelance API work in Nepal.',
        'keywords' => [
            'Madhusudan Timalsina',
            'Backend Developer Nepal',
            'Laravel developer',
            'REST API developer',
            'Node.js developer',
            'Python backend',
            'database design',
            'Smartsarka',
            'freelance backend developer',
            'Apex College BCIS',
        ],
        'image' => '/images/1738049302099.jpg',
        'image_alt' => 'Madhusudan Timalsina, Backend Developer',
        'locale' => 'en_US',
        'theme_color' => '#F3EBD9',
        'pages' => [
            'home' => [
                'path' => '/',
                'title' => 'Madhusudan Timalsina | Backend Developer',
                'description' => 'Backend Developer at Smartsarka Pvt. Ltd. building Laravel APIs, databases and server-side systems. Explore projects, skills and freelance backend services by Madhusudan Timalsina.',
                'h1' => 'Madhusudan Timalsina — Backend Developer',
            ],
            'about' => [
                'path' => '/about',
                'title' => 'About Madhusudan Timalsina | Backend Developer at Smartsarka',
                'description' => 'Learn about Madhusudan Timalsina, Backend Developer at Smartsarka Pvt. Ltd. — production APIs, Laravel systems, database design and BCIS studies at Apex College.',
                'h1' => 'About Madhusudan Timalsina',
            ],
            'skills' => [
                'path' => '/skills',
                'title' => 'Backend Skills | Laravel, Node.js, Python & APIs',
                'description' => 'Technical skills of Madhusudan Timalsina: Laravel, Node.js, Python, REST APIs, database design, authentication flows and freelance backend capabilities.',
                'h1' => 'Backend skills & stack',
            ],
            'projects' => [
                'path' => '/projects',
                'title' => 'Backend Projects | Laravel, APIs & Full-Stack Builds',
                'description' => 'Featured projects by Madhusudan Timalsina — Laravel e-commerce, marketplace platforms, Flutter apps and database-backed products that showcase backend and full-stack delivery.',
                'h1' => 'Projects & backend builds',
            ],
            'education' => [
                'path' => '/education',
                'title' => 'Education & Leadership | BCIS Apex College',
                'description' => 'Education background of Madhusudan Timalsina: BCIS at Apex College, SMART Program mentoring, campus tech leadership and continuous backend learning.',
                'h1' => 'Education & career highlights',
            ],
            'contact' => [
                'path' => '/contact',
                'title' => 'Contact Madhusudan Timalsina | Hire a Backend Developer',
                'description' => 'Contact Madhusudan Timalsina for Laravel API work, database design and freelance backend development. Currently Backend Developer at Smartsarka Pvt. Ltd., based in Nepal.',
                'h1' => 'Hire a Backend Developer',
            ],
        ],
        'faqs' => [
            [
                'question' => 'What does Madhusudan Timalsina specialize in?',
                'answer' => 'Madhusudan Timalsina is a Backend Developer specializing in Laravel, Node.js, Python, REST APIs, authentication flows and database design for production applications.',
            ],
            [
                'question' => 'Where does Madhusudan currently work?',
                'answer' => 'Madhusudan works as a Backend Developer at Smartsarka Pvt. Ltd., building and maintaining server-side systems, APIs and database features in a production environment.',
            ],
            [
                'question' => 'Is Madhusudan available for freelance backend work?',
                'answer' => 'Yes. Alongside the Smartsarka role, Madhusudan takes selective freelance work for Laravel features, API development, database schema planning and related backend support.',
            ],
            [
                'question' => 'How can I contact Madhusudan Timalsina?',
                'answer' => 'You can reach Madhusudan by email at timmadh@gmail.com, WhatsApp at +977 9861333037, or LinkedIn at madhusudan-timalsina.',
            ],
            [
                'question' => 'What technologies does Madhusudan use for backend development?',
                'answer' => 'Core technologies include Laravel, Node.js, Python, REST APIs, SQLite and relational database design, plus auth and CRUD systems for web and mobile clients.',
            ],
        ],
    ],
    'footer' => '© '.date('Y').' Madhusudan Timalsina. All rights reserved.',
];
