<?php

return [
    'brand' => 'Madhusudan Timalsina',
    'name' => 'Madhusudan',
    'full_name' => 'Madhusudan Timalsina',
    'title' => 'Backend Developer',
    'location' => 'Nepal',
    'badge' => 'BCIS Student · Apex College · Open to Backend Roles',
    'headline' => 'I build the APIs, databases and server logic that power real products.',
    'bio' => 'Backend-focused BCIS student and developer specializing in Laravel, Node.js, Python, REST APIs and database design. I structure reliable server-side systems, model clean data and ship features that stay maintainable as products grow.',
    'backend_intro' => 'As a Backend Developer I focus on how data moves, how APIs stay consistent and how authentication, business rules and database design support the product — whether for college builds, freelance clients, or team projects.',
    'backend_highlights' => [
        [
            'title' => 'API development',
            'desc' => 'Designing and implementing REST endpoints, request validation and clear response contracts for web and mobile clients.',
        ],
        [
            'title' => 'Laravel backend',
            'desc' => 'Routes, controllers, services, authentication flows and modular features for real application use cases.',
        ],
        [
            'title' => 'Database design',
            'desc' => 'Schema planning, relationships, CRUD systems and administration so data stays consistent and queryable.',
        ],
        [
            'title' => 'Node.js & Python',
            'desc' => 'Server-side scripting and backend services alongside Laravel when the project needs flexible tooling.',
        ],
        [
            'title' => 'Auth & business logic',
            'desc' => 'User flows, permissions-minded structure and server rules that protect data and keep apps predictable.',
        ],
        [
            'title' => 'Freelance backend support',
            'desc' => 'Feature work, bug fixes and database setup for clients who need solid server-side delivery.',
        ],
    ],
    'backend_stack' => ['Laravel', 'Node.js', 'Python', 'REST APIs', 'Database Design', 'SQLite', 'Auth flows', 'CRUD systems'],
    'about_intro' => 'I am a BCIS student at Apex College focused on backend development — APIs, databases and server-side architecture — while also shipping full products when projects need end-to-end delivery.',
    'about_story' => [
        'My path into development started with curiosity about how websites and apps actually work — then grew into building complete products from design through database and deployment thinking.',
        'During my BCIS studies at Apex College I have worked on platforms for book trading, fashion e-commerce, food discovery for renters and personal fitness tracking. Each project taught me something new about UX, data modeling and shipping under deadlines.',
        'Alongside coursework I take on freelance development work — helping clients and small teams turn ideas into working web and mobile solutions. I also mentor peers through the SMART Program, organize tech events and serve as a class representative.',
    ],
    'about_focus' => [
        'Designing clear, usable interfaces for web and mobile',
        'Building backend logic with Laravel, Node.js and Python',
        'Structuring databases so applications stay reliable',
        'Collaborating through communication, mentoring and teamwork',
        'Delivering freelance projects with clear scope and communication',
        'Learning new tools quickly and applying them on real builds',
    ],
    'values' => [
        [
            'title' => 'Clarity first',
            'desc' => 'I prefer simple interfaces and readable code so products stay easy to use and maintain.',
        ],
        [
            'title' => 'End-to-end thinking',
            'desc' => 'I care about the full flow — UI, API, database and how users actually move through the product.',
        ],
        [
            'title' => 'Reliable delivery',
            'desc' => 'Whether for college or freelance clients, I focus on finishing work that is usable, tested and documented enough to continue.',
        ],
        [
            'title' => 'Learning in public',
            'desc' => 'Mentoring, judging and organizing campus tech activities keep me sharp and connected to the community.',
        ],
    ],
    'services' => [
        [
            'title' => 'Website development',
            'desc' => 'Business sites, landing pages and content-driven websites with clean layouts and responsive design.',
        ],
        [
            'title' => 'Laravel applications',
            'desc' => 'Custom web apps with authentication, CRUD modules, dashboards and structured database work.',
        ],
        [
            'title' => 'Mobile app UI & Flutter',
            'desc' => 'Cross-platform app screens and flows in Flutter, including local storage with SQLite where needed.',
        ],
        [
            'title' => 'Database design',
            'desc' => 'Schema planning, relationships and administration so your app data stays consistent and queryable.',
        ],
        [
            'title' => 'Frontend implementation',
            'desc' => 'React and modern UI builds that match a design system and feel polished on desktop and mobile.',
        ],
        [
            'title' => 'Freelance support',
            'desc' => 'Short-term feature work, fixes and product improvements for startups, students and small businesses.',
        ],
    ],
    'email' => 'timmadh@gmail.com',
    'email_href' => 'https://mail.google.com/mail/?view=cm&fs=1&to=timmadh@gmail.com',
    'phone' => '+977 9861333037',
    'phone_href' => 'https://wa.me/9779861333037',
    'social' => [
        'linkedin' => 'https://www.linkedin.com/in/madhusudan-timalsina-75a910183/',
    ],
    'palette' => [
        'bg' => '#05070d',
        'ink' => '#E8EEF7',
        'coral' => '#2DD4BF',
        'yellow' => '#F59E0B',
        'mint' => '#14B8A6',
        'blue' => '#60A5FA',
        'card' => 'rgba(12, 18, 32, 0.72)',
        'soft' => 'rgba(148, 163, 184, 0.12)',
    ],
    'requests' => [
        ['method' => 'GET', 'path' => '/api/profile', 'status' => 200, 'color' => 'mint'],
        ['method' => 'POST', 'path' => '/api/auth/login', 'status' => 201, 'color' => 'yellow'],
        ['method' => 'GET', 'path' => '/api/projects', 'status' => 200, 'color' => 'blue'],
        ['method' => 'PUT', 'path' => '/api/skills', 'status' => 200, 'color' => 'coral'],
    ],
    'stack' => [
        [
            'label' => 'Frontend',
            'icon' => 'layout',
            'color' => 'blue',
            'tools' => ['React', 'Flutter', 'Web Design', 'UI Development', 'Responsive Layout'],
            'blurb' => 'Responsive interfaces for web and mobile, built with clarity and usability in mind.',
            'details' => 'I design and implement user-facing screens for websites and apps — focusing on hierarchy, accessibility of basic interactions and smooth experiences across phone and desktop.',
        ],
        [
            'label' => 'Backend',
            'icon' => 'server',
            'color' => 'coral',
            'tools' => ['Laravel', 'Node.js', 'Python', 'REST APIs', 'Auth flows'],
            'blurb' => 'Application logic, APIs and server-side architecture that keep products stable and scalable.',
            'details' => 'Comfortable building server-side features in Laravel and Node.js, wiring routes, services and form/API handling so the frontend has a solid foundation.',
        ],
        [
            'label' => 'Database',
            'icon' => 'database',
            'color' => 'mint',
            'tools' => ['Database Design', 'SQLite', 'Data Modeling', 'Administration', 'CRUD systems'],
            'blurb' => 'Structured data models and administration so applications stay fast and consistent.',
            'details' => 'From college platforms to personal apps, I plan tables/relationships, manage data integrity and keep admin-facing workflows practical.',
        ],
        [
            'label' => 'Practices',
            'icon' => 'wrench',
            'color' => 'yellow',
            'tools' => ['Design Thinking', 'Problem-Solving', 'Project Management', 'Communication', 'Mentoring'],
            'blurb' => 'Collaborative delivery, clear communication and practical problem-solving across teams.',
            'details' => 'As a class representative and SMART mentor, I practice coordination, feedback and breaking work into shippable pieces — skills I also use with freelance clients.',
        ],
    ],
    'languages' => [
        ['name' => 'Laravel', 'level' => 'Strong project experience', 'note' => 'Used on Yfasma and related web builds'],
        ['name' => 'Flutter', 'level' => 'Strong project experience', 'note' => 'Swaad Sathi and Gym App'],
        ['name' => 'React', 'level' => 'Applied on projects', 'note' => 'Frontend interfaces and component UI'],
        ['name' => 'Node.js', 'level' => 'Applied on projects', 'note' => 'Backend services and API work'],
        ['name' => 'Python', 'level' => 'Working knowledge', 'note' => 'Scripting and backend learning'],
        ['name' => 'React Native', 'level' => 'Project exposure', 'note' => 'Mobile flows on Swaad Sathi'],
    ],
    'soft_skills' => [
        'Strong communication with teammates and stakeholders',
        'Project coordination and deadline awareness',
        'Design thinking and user-focused problem solving',
        'Computer literacy across common development tooling',
        'Leadership as class representative for 42 students',
        'Mentoring and peer support through SMART Program',
    ],
    'projects' => [
        [
            'name' => 'Thrift Books',
            'tag' => 'FULL-STACK',
            'period' => 'Jul–Sep 2023',
            'type' => 'College project',
            'desc' => 'A platform for buying and selling second-hand books with dynamic frontend and backend flows, plus database administration for listings and transactions.',
            'long_desc' => 'Thrift Books was built to make second-hand book trading simpler for students. I worked across website design and database administration so users could browse listings, manage posts and complete buy/sell flows through a dynamic full-stack experience.',
            'highlights' => [
                'End-to-end website design for buying and selling used books',
                'Database administration for listings, users and transactions',
                'Dynamic frontend and backend integration',
                'Focused on a practical campus marketplace use case',
            ],
            'stack' => ['Web Design', 'Database', 'Full-Stack'],
            'color' => 'coral',
            'url' => '#',
        ],
        [
            'name' => 'Yfasma',
            'tag' => 'LARAVEL',
            'period' => 'May–Jul',
            'type' => 'College project',
            'desc' => 'An e-commerce website for affordable designer clothing. Built with Laravel, covering database administration, site structure and end-to-end web delivery.',
            'long_desc' => 'Yfasma is a clothing e-commerce concept that helps users buy designed apparel at affordable prices. I used Laravel to structure the website and database, deepening my understanding of how real Laravel apps are organized from routes to views.',
            'highlights' => [
                'Laravel-based website architecture',
                'Database design and administration for catalog/content',
                'Product-oriented UI for browsing designer clothing',
                'Hands-on practice with Laravel web development patterns',
            ],
            'stack' => ['Laravel', 'Database', 'Web Design'],
            'color' => 'blue',
            'url' => '#',
        ],
        [
            'name' => 'Swaad Sathi',
            'tag' => 'MOBILE',
            'period' => 'May–Jul',
            'type' => 'College project',
            'desc' => 'A mobile app connecting renters with nearby home kitchens. Frontend built with Flutter and React Native, including AI chatbot integration for guided assistance.',
            'long_desc' => 'Swaad Sathi connects people living in rental housing — who often lack time to cook — with home kitchens and cloud-kitchen style providers. I worked on frontend design and development in Flutter and React Native and explored AI chatbot integration with manual training for guided assistance.',
            'highlights' => [
                'Mobile-first experience for renters and home kitchens',
                'Frontend development with Flutter and React Native',
                'AI chatbot integration for guided user help',
                'Solves a real lifestyle problem around daily meals',
            ],
            'stack' => ['Flutter', 'React Native', 'AI Chatbot'],
            'color' => 'mint',
            'url' => '#',
        ],
        [
            'name' => 'Gym App',
            'tag' => 'FLUTTER',
            'period' => 'Sep–Oct',
            'type' => 'Personal project',
            'desc' => 'A personal fitness tracker built with Flutter and SQLite for local activity logging and progress tracking.',
            'long_desc' => 'A personal-use fitness app built to track my own workouts and activity. I implemented the frontend in Flutter and used SQLite for local data storage so progress could be saved offline without a heavy backend.',
            'highlights' => [
                'Flutter frontend for activity tracking',
                'SQLite local database for saving progress',
                'Built for personal daily use and iteration',
                'Practical experience with offline-first mobile data',
            ],
            'stack' => ['Flutter', 'SQLite'],
            'color' => 'yellow',
            'url' => '#',
        ],
    ],
    'freelance' => [
        'intro' => 'Beyond college coursework, I take freelance development work — helping individuals and small teams ship websites, Laravel features and mobile UI. Engagements typically range from landing pages and admin panels to app screens and database setup.',
        'offers' => [
            'Custom website builds and redesigns',
            'Laravel feature development and bug fixes',
            'Flutter screen implementation and polish',
            'Database schema planning for new products',
            'UI improvements based on design thinking feedback',
            'Short consulting calls to clarify technical scope',
        ],
    ],
    'education' => [
        [
            'degree' => 'Bachelor in Computer Information System',
            'school' => 'Apex College',
            'period' => '2020 – Present',
            'details' => 'Studying computer information systems with a focus on software development, databases and practical project work. Coursework and campus projects cover web development, application design and collaborative delivery.',
            'points' => [
                'Active in campus tech events and workshops',
                'Class representative for a cohort of 42 students',
                'Applied classroom concepts through multiple shipped college projects',
            ],
        ],
        [
            'degree' => 'Secondary Level',
            'school' => 'Advance Academy',
            'period' => '2015 – 2017',
            'details' => 'Completed secondary education at Advance Academy, building the academic foundation that led into BCIS and hands-on technology study.',
            'points' => [
                'Strong base for further IT and business-systems study',
                'Continued interest in technology and problem-solving',
            ],
        ],
    ],
    'achievements' => [
        [
            'title' => 'Class representative',
            'desc' => 'Represented a cohort of 42 students — coordinating communication, supporting peers and helping connect classmates with faculty.',
        ],
        [
            'title' => 'SMART Program mentor',
            'desc' => 'Mentored a full section in the SMART Program. The team earned Best Team recognition twice, strengthening my leadership and coaching skills.',
        ],
        [
            'title' => 'SMART Program judge',
            'desc' => 'Participated as a judge in the SMART Program, reviewing work and providing constructive feedback to participating teams.',
        ],
        [
            'title' => 'Campus tech organizer',
            'desc' => 'Helped organize technology events and workshops at college, supporting learning beyond the classroom.',
        ],
        [
            'title' => 'Self-driven learning',
            'desc' => 'Built web development and database skills through self-study alongside formal coursework, then applied them in real projects.',
        ],
        [
            'title' => 'Academic consistency',
            'desc' => 'Maintained strong performance in key IT courses throughout college while balancing projects and leadership roles.',
        ],
    ],
    'process' => [
        [
            'step' => '01',
            'title' => 'Understand the goal',
            'desc' => 'Clarify who the product is for, what problem it solves and what “done” looks like.',
        ],
        [
            'step' => '02',
            'title' => 'Structure the system',
            'desc' => 'Sketch screens, data models and key flows before heavy coding begins.',
        ],
        [
            'step' => '03',
            'title' => 'Build in iterations',
            'desc' => 'Ship usable pieces early — UI, backend and database — then refine with feedback.',
        ],
        [
            'step' => '04',
            'title' => 'Polish and hand off',
            'desc' => 'Clean up edge cases, document basics and make sure the product is ready for real use.',
        ],
    ],
    'nav' => [
        ['label' => 'Home', 'route' => 'home'],
        ['label' => 'About', 'route' => 'about'],
        ['label' => 'Skills', 'route' => 'skills'],
        ['label' => 'Projects', 'route' => 'projects'],
        ['label' => 'Education', 'route' => 'education'],
    ],
    'contact' => [
        'title' => 'Let’s build the backend.',
        'blurb' => 'Open to backend developer roles, internships, freelance API/database work and collaborative builds in Laravel, Node.js and Python.',
        'availability' => 'Available for freelance backend projects and internship conversations. Usually respond within 24–48 hours.',
        'looking_for' => [
            'Junior / entry-level Backend Developer roles',
            'Internships focused on APIs, Laravel, or databases',
            'Freelance Laravel and API feature work',
            'Database design and backend architecture for small products',
            'Team projects where I can own server-side delivery',
        ],
        'topics' => [
            'REST API design and Laravel backends',
            'Database schema for a new product',
            'Auth, CRUD modules and admin APIs',
            'Node.js / Python backend support',
            'Freelance or internship collaboration',
        ],
    ],
    'footer' => '© '.date('Y').' Madhusudan Timalsina. All rights reserved.',
];
